# Generated by Django 4.1.7 on 2023-03-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_task_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='high', max_length=100),
            preserve_default=False,
        ),
    ]
